baseURL = "/"
languageCode = "en-us"
title = "Nick is cooking..."
theme = "ananke"

recent_posts_number = 10

enableGitInfo = true

[params]
  body_classes = "avenir bg-washed-green dark-green"
  post_content_classes = "dark-green bg-washed-green"
  background_color_class = "bg-dark-green"

[services.disqus]
  shortname = 'nick-is-cooking'