baseURL = "/"
languageCode = "en-us"
title = "Nick is cooking..."
theme = "ananke"

recent_posts_number = 10

enableGitInfo = true

[params]
  body_classes = "avenir bg-washed-orange dark-green"
  post_content_classes = "dark-green"
  background_color_class = "bg-dark-green"
